### ISSUE TITLE
Missing /app-modules/*/src/View/Components

### ISSUE THREAD

**Issue by dcblogdev** [InterNACHI/modular#19]
First, thank you for this package it looks brilliant.

I've installed it on a fresh Laravel 8.33.1 project when I make a module I see a terminal error for missing folders:

```
 The "/app-modules/*/src/View/Components" directory does not exist.
```

I have to create the folders View/Components in src.

And 

```
The "/app-modules/*/src/Models" directory does not exist.
```

This is for the first module only a second module works without these directories with no problem.

**Comment by inxilpro** [comment]
Sorry it's taken me some time to get to this. I'm looking into it now!

**Comment by laurence702** [comment]
please merge fix into main. good work @inxilpro
