### ISSUE TITLE
don't use option command --migration or -m in make model

### ISSUE THREAD

**Issue by P-Shakibafar** [InterNACHI/modular#2]
when use make:model command can not use option command -mfrv for generate migration ,factory, controller with model.

**Comment by inxilpro** [comment]
This should be sorted out in the next few days. Trying to find the least-invasive way to do this—we want to avoid re-implementing as much of the `make:` command logic as possible.

**Comment by inxilpro** [comment]
This is taking longer to address because the base classes have the namespace hard-coded in a way that's hard to work around without writing a bunch of brittle logic. I think I'm close to a solution, though. Sorry for the long delay!

**Comment by inxilpro** [comment]
I think version 1.1.0 fixes this!
