### ISSUE TITLE
Livewire support

### ISSUE THREAD

**Issue by dcblogdev** [InterNACHI/modular#20]
Are there any plans to support `make:livewire` for projects with Livewire installed ie:

```
make:livewire ContactForm --module=Pages
```

**Comment by inxilpro** [comment]
It's not currently on the roadmap. When we looked into this before (@DanielCoulbourne — correct me if I'm wrong), Livewire doesn't support loading components from multiple namespaces. Until that changes, I don't think that we can do much to add support on our end.
