### ISSUE TITLE
Non support with swagger

### ISSUE THREAD

**Issue by laurence702** [InterNACHI/modular#25]
Dear @inxilpro et all. I so much love this InterNachi modular package, the only pitfall I've found with it is non-support with swagger documentation. I'm using [L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger) package for this. when I try to generate documentation using php artisan l5-swagger:generate, i get ErrorException: Required @OA\PathItem() not found. despite having annotations and all properly done. it appears the swagger packager doesn't look through the modules. Can you suggest any fix for this. Im gona open an issue on the L5 swagger github page also.

**Comment by inxilpro** [comment]
I've never used that package before so I can't say for sure. That exception seems odd. Did you add `app-modules` to the annotations section of the config file?

**Comment by laurence702** [comment]
> I've never used that package before so I can't say for sure. That exception seems odd. Did you add `app-modules` to the annotations section of the config file?

Thanks alot @inxilpro that was the solution to get this to work. 

            ```
    /*
                 * Absolute paths to directory containing the swagger annotations are stored.
                */
                'annotations' => [
                    //base_path('app'), I changed from this 
                    base_path('app-modules'),  // now to this
                ],
```

Now i don't have abandon Modular just to use Swagger

**Comment by inxilpro** [comment]
By the looks of it you can probably have both:

```php
'annotations' => [
  base_path('app'),
  base_path('app-modules'),
],
```

That way it'll look in your root app and in your modules.

That said, if you only have annotations inside modules, and nothing in you root app, it's perfectly fine to just swap it out.

**Comment by laurence702** [comment]
> By the looks of it you can probably have both:
> 
> ```
> 'annotations' => [
>   base_path('app'),
>   base_path('app-modules'),
> ],
> ```
> 
> That way it'll look in your root app and in your modules.
> 
> That said, if you only have annotations inside modules, and nothing in you root app, it's perfectly fine to just swap it out.

yeah I already tried that, having the two module paths as an array, doesn't work, its a thing with the L5 swagger package, im totally fine with having just one module path for my code base. thanks for the suggestion and help on this :)
