### ISSUE TITLE
Make Hyphen Configurable when StudlyCaps Name Spacing is Used

### ISSUE THREAD

**Issue by djallits** [InterNACHI/modular#3]
Our organizational Namespace is **FarmJournal**. Our GitHub org name is **farmjournal**.

### Current State
When a user runs the following command `$ php artisan make:module acme`:

```
...
Module cache cleared!
Please run composer update farm-journal/acme
```

### Preferred State
When a user runs the following command `$ php artisan make:module acme`:

```
...
Module cache cleared!
Please run composer update farmjournal/acme
```

### Proposed Solution 1 
Add a new config option that allows a boolean value to be set to enable/disable hyphenation of user or org namespace.

### Proposed Solution 2
Add a new config option that allows a string value to be set for use of a user or org namespace.

**Comment by inxilpro** [comment]
This is the `modules_vendor` configuration option. In your case, you want to set:

```php
return [
  'modules_namespace' => 'FarmJournal',
  'modules_vendor' => 'farmjournal',
  // ...
];
```

**Comment by djallits** [comment]
Thanks @inxilpro

I posted this 11 days ago, but I see you added the `modules_vendor` config 23 days ago. I wonder how I missed this.

Sorry!

**Comment by inxilpro** [comment]
No prob! Sorry it took me a bit to get back to you.
