### ISSUE TITLE
[Question] Web middleware

### ISSUE THREAD

**Issue by robsontenorio** [InterNACHI/modular#31]
Hi!

On my default laravel "top level app" I have such kernel/http middleware.

```
 protected $middlewareGroups = [
        'web' => [
         ...
            \App\Http\Middleware\HandleInertiaRequests::class,
        ],
```

I just noticed this is only applied to "top level app", it does not have effect on `app-modules`.

Is the any special config do I need? This such thing should not working out of box?

**Comment by robsontenorio** [comment]
Ok, just set `middleware('web')` group on  `yyy-routes.php` file and it works. Is that expected?

```
Route::middleware('web')->group(function () {
   // my modules routes
});
```

**Comment by inxilpro** [comment]
Yep, you need to set the middleware as a group for your modules. It's an interesting point, though. I'm not sure if it makes sense for modules to pick up the default middleware groups in your `RouteServiceProvider`. It's something I'll keep an eye out for and maybe consider if other people get caught off guard by that.

**Comment by inkomomutane** [comment]
> I'd suggest adding a note on that to the readme.
Agree with you. I took more than one hour to figure out that. 
@inxilpro
