### ISSUE TITLE
The "--module" option does not exist Livewire and Migrations

### ISSUE THREAD

**Issue by dcblogdev** [InterNACHI/modular#35]
Hi, I've noticed running these commands doesn't have the --module option. This is using Laravel 9.19.0

This is on a fresh install

Migration:
```
php artisan make:migration create_pages_table --module=pages
```

Livewire:
```
php artisan  make:livewire contact --module=pages
```

Both trigger: 
>  The "--module" option does not exist.

**Comment by inxilpro** [comment]
Can you run the following command in `php artisan tinker`?

```
get_class(app('command.migrate.make'));
```

It should return `"InterNACHI\Modular\Console\Commands\Make\MakeMigration"`

**Comment by dcblogdev** [comment]
yes, I do get back:

```
Psy Shell v0.11.6 (PHP 8.1.4 — cli) by Justin Hileman
>>> get_class(app('command.migrate.make'));
=> "InterNACHI\Modular\Console\Commands\Make\MakeMigration"
```

**Comment by inxilpro** [comment]
Can you try:

```shell
composer require internachi/modular:dev-main
```

And confirm that both commands now work for you? I have it working locally, but it's a little bit of a tricky issue (has to do with the order of how commands are loaded by Laravel) so I'd love another real-world confirmation that this fixes it.

**Comment by dcblogdev** [comment]
yes, that works for both commands.

I may have found another problem but it could be out of scope.

When creating a livewire comoinent I see this:

```
dave@dcblog modular % php artisan  make:livewire contact --module=contacts
 COMPONENT CREATED  🤙

CLASS: app/Dcblogdev/Contacts/Http/Livewire/Contact.php
VIEW:  app-modules/contacts/resources/views/livewire/contact.blade.php
```
the class contains an incorrect page to a view:

```
<?php

namespace Dcblogdev\Contacts\Http\Livewire;

use Livewire\Component;

class Contact extends Component
{
    public function render()
    {
        return view('users.dave.dropbox(-the-one-point-limited).local.personal.modular.app-modules.contacts.resources.views.livewire.contact');
    }
}
```

**Comment by inxilpro** [comment]
@dcblogdev can you open that as a second issue? The Livewire support is a little tricky, but I'm sure we can come up with a fix.

**Comment by artisanbr** [comment]
I made a pull request with a correction to this problem, I can use it normally now with my fork...

I hope the project can benefit from this contribution.
Commit:
#59
