### ISSUE TITLE
The "--module" option don't work for controller

### ISSUE THREAD

**Issue by jrmessias** [InterNACHI/modular#36]
Hi,

I am testing this package for modularize my projects.

I started instalation like the documentation.

I created a module, and after create a controller. But when i create a controller, the controler has been created in 'app/http/controllers' not in 'app-modules/module/http/controllers'.

The command I used is php artisan make:controller Backend/MyModuleController --module=my-module

Please, can help me?

What I did wrong?

(sorry the English)

**Comment by dcblogdev** [comment]
I've just run this on my own project and the controller is created in the correct folder.

I've recorded a quick video showing the process https://watch.screencastify.com/v/qYlOneExahoNinLyrAOI

**Comment by inxilpro** [comment]
@dcblogdev thanks for putting together that screencast! I've also confirmed that it seems to be working OK on a fresh install (there are also tests that cover the `make:controller` command that are passing).

@jrmessias did you run `php artisan make:module my-module` first? I think maybe the issue is that if you pass a `--module` option and that module doesn't exist, the command just runs normally. There should definitely be an error in that case.

**Comment by inxilpro** [comment]
@jrmessias Give version 1.9.0 a try. That should have better error reporting for you. I'm guessing that the issue is that you're passing `--module=my-module` but used a name other than `"my-module"` when calling `make:module`.

If that's not the case, feel free to reopen this issue!

**Comment by jrmessias** [comment]
> I've just run this on my own project and the controller is created in the correct folder.
> 
> I've recorded a quick video showing the process https://watch.screencastify.com/v/qYlOneExahoNinLyrAOI

Thanks for the video

**Comment by jrmessias** [comment]
> @dcblogdev thanks for putting together that screencast! I've also confirmed that it seems to be working OK on a fresh install (there are also tests that cover the `make:controller` command that are passing).
> 
> @jrmessias did you run `php artisan make:module my-module` first? I think maybe the issue is that if you pass a `--module` option and that module doesn't exist, the command just runs normally. There should definitely be an error in that case.

Thanks for the help.

I run `php artisan make:module my-module` first, to create the module.

I used on my existent project and on a new fresh installation of laravel (like video), the bug still happen.

Maybe the problem is SO? I use Windows (just thinking).

Thanks.
