### ISSUE TITLE
Config file hierarchy

### ISSUE THREAD

**Issue by Sophist-UK** [InterNACHI/modular#43]
When I create a module it may have it's own composer prerequisite packages.

I use [wikimedia composer merge](https://github.com/wikimedia/composer-merge-plugin) to do a global install of prerequisite packages including those in the modules.

Suppose I install (say) Laravel Debugbar as a pre-requisite package for a specific module. The package comes with a publishable vendor config file. I may or may not wish to tailor that config file as part of the module. The site owner may want to publish and tweak the original config file or the one I have already tweaked for the module.

IMO this hierarchy of config files is something that needs to be handled, both normally and when config caching is turned on.

Is there any code in **modular** to handle this?

**Comment by inxilpro** [comment]
Hm, this feels outside the scope of modular IMHO. I could be wrong, but that's my gut reaction. Modular isn't really for user-installed modules. If that's what you need, `nWidart/laravel-modules` is probably a better fit.

Modular is really just for organizing a single project, in which case you can just publish the config file and be done with it.

Is there something I'm missing? Or a use-case that I haven't thought of?

**Comment by Sophist-UK** [comment]
If the use case is only for modules that you never publish later as packages, I agree.

I tried `nWidart/laravel-modules` before `interNACHI/modular`, but the fundamental approach to identifying modules used by nWidart is badly chosen and **VERY** poorly performing i.e. it doesn't maintain a list of modules to load, but instead searches for them on every run of Laravel!!!! I doubt that this is easily fixable.

So, it would be useful for me if `modular` supported modules as packages too - so this sort of functionality would be useful.

I would be happy to research how nWidart does it and submit a PR to something similar here.

**Comment by inxilpro** [comment]
Can you point to a package somewhere that already does this? Or where `nWidart/laravel-modules` does this? As far as I understand how config files are loaded, there really is no way to support this without some pretty ugly hacks. If you look at how Laravel loads configs in [`LoadConfiguration`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php) you'll see that there just aren't really any hooks in place for something like this…

**Comment by Sophist-UK** [comment]
https://github.com/nWidart/laravel-modules/pull/1419 though this PR got screwed up when the mods reverted a previous PR that made the performance issues far worse.

In essence, in laravel-modules the service provider stub deals with module's own config files as standard. I created a trait that extended the functionality to add a function to handle the config hierarchy when the module uses a package and that package has a config file ttps://github.com/Sophist-UK/laravel-modules/blob/39dd782f68c31cc3ff5649ca79c0b5bbcb277b5f/src/Laravel/ModuleConfigMerge.php.

**Comment by inxilpro** [comment]
This feels like something you can just do in your own module as needed… apply the `ModuleConfigMerge` logic inside your module's service provider for the packages that you want to adjust the settings for. It feels too much of an edge-case to build into modular.

**Comment by Sophist-UK** [comment]
Well I can certainly build it in to my own code - but equally happy to submit it as a PR if you want to make it available to others if they need it.

**Comment by Orrison** [comment]
@Sophist-UK did you happen to end up building out this functionality in your code? And if so, would you mind sharing details on how you did so?

I agree that this functionality is wanted and very useful.
