### ISSUE TITLE
Multiple Folders 

### ISSUE THREAD

**Issue by ifarsolutions** [InterNACHI/modular#46]
Is there a way to create subfolders to arrange my modules?

Eg:- Let's say i have auth modules, dashboard modules, theme modules

I want to arrange it into folders 

Inside a folder called core, i can add auth & dashboard modules then inside another folder i can name it packages then i have theme modules there.

`        {
            "type": "path",
            "url": "Modules/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "Modules/core/*",
            "options": {
                "symlink": true
 `

**Comment by adrienne** [comment]
@ifarsolutions did you figure out how to do this? I need this as well.

**Comment by ifarsolutions** [comment]
@adrienne No, unfortunately, i couldn't find it, i had to drop this solution and built my own package.

**Comment by inxilpro** [comment]
Sorry—somehow missed this. As of right now, we don't support nesting of modules. I could see the argument for adding that at some point in the future, though…

**Comment by adrienne** [comment]
@inxilpro - at least in my case, I don't need *nested* modules; I just need two separate folders which can each contain modules. It's because I have two separate spheres of concern in the app -- almost subsites -- and i would like to keep the modules for them separated.
