### ISSUE TITLE
Sub Modules

### ISSUE THREAD

**Issue by akhalid4493** [InterNACHI/modular#49]
If I need to build a large app, how can I create submodules within the main module, such as:

* nventory Module

- Products submodule
- Category submodule
- Stock submodule
* Ordering Module
  - Checkout submodule
  - Cart submodule
  - Payment submodule

**Comment by akhalid4493** [comment]
If I need to build a large app, how can I create submodules within the main module, such as:

* nventory Module

- Products submodule
- Category submodule
- Stock submodule
* Ordering Module
  - Checkout submodule
  - Cart submodule
  - Payment submodule

**Comment by inxilpro** [comment]
Hm. As of right now this isn't supported. I would just use a naming convention, honestly…

```md
- app-modules
  - inventory
  - inventory-products
  - inventory-categories
  - inventory-stock
  - ordering
  - ordering-checkout
  - ordering-cart
  - ordering-payment
```

I think that submodules is probably outside of the scope of this package.

**Comment by galliroberto** [comment]
Is simple to achive sub module.

I have to change 'modules_directory' to when I want create and use command for submodule 'app-modules/organization/app-modules'

To achive it, put modules_directory in .env file and pass a value of the modules_directory when you execute commands

`'modules_directory' => env('MODULES_DIR', 'app-modules'),`

I use ddev
`ddev exec MODULES_DIR="app-modules/organization/app-modules" artisan make: ....`


In this way I have grouped sub module in a folder.
If you want you can create a parent module with sub module. The parent module is a common layer, you can achive the same things with a common module required in composer.json of submodule

![image](https://github.com/user-attachments/assets/4cec7b9c-87a9-4097-9fba-9d730000f0a1)
