### ISSUE TITLE
Filament Support

### ISSUE THREAD

**Issue by dgoetzit** [InterNACHI/modular#51]
Hi @inxilpro!

My team and I love the package, and are interested in using this in combination with a [Filament](https://github.com/filamentphp/filament) application we are working on. We are specifically looking for the ability to `make` Filament resources in the context of a module. We are absolutely happy to contribute in making this happen, but we wanted to get your opinion on the best way to make this happen as one of the maintainers. 

Given there are potentially hundreds of other packages that add some sort of `make` functionality through Artisan commands, does it make sense to extract each of those into their own _modules_ for support? If that is the case, we'd be happy to help take on the splitting of Livewire into its own dependency, as well as the introduction of a Filament package to do the same. Let me know what you think of this approach, or if you have any other ideas in mind to accomplish this. 

Thank you!

cc @Orrison @bogdankharchenko

**Comment by inxilpro** [comment]
I think I'm fine with adding filament support directly into the modular package, as long as it's relatively contained. Would you be willing to PR it and if it feels like it's getting out of hand we can always move it to a separate repo?

**Comment by dgoetzit** [comment]
Sounds like a plan, thanks @inxilpro!

**Comment by inxilpro** [comment]
Sounds good. I'll close this for now and keep an eye out for a PR. Thanks for contributing!

**Comment by awcodes** [comment]
@dgoetzit Are you working on this? I don't want to start it if you are actively working on it.

**Comment by Orrison** [comment]
@awcodes, we apologize, this actually should most likely no longer be needed. Filament should now work with this out of the box if your module registers a Filament plugin that discovers resources. See https://github.com/canyongbs/assistforhighered-2/blob/develop/app-modules/case/src/CasePlugin.php and https://github.com/canyongbs/assistforhighered-2/blob/develop/app-modules/case/src/Providers/CaseServiceProvider.php

After setting up in this way Filament will ask you which namespace you would like the make command to run in.

**Comment by Orrison** [comment]
But if there is something more you need to do. No, we are most likely not going to be working on this.

**Comment by awcodes** [comment]
Thanks. I'll give it a go. Tried it today and it just didn't work the way I expected. Probably my fault. Thanks for the reply.

**Comment by awcodes** [comment]
Actually I was referring to the --modules flag. So I can run `make:filament-resource Post --module=blog`.

No problems with registering the resource with a panel.

**Comment by awcodes** [comment]
It's my understanding that to support 3rd party artisan actions a PR would be needed to the package, or is it possible to hook in with a provider to do this without an addition to core?

**Comment by dgoetzit** [comment]
@awcodes We did not find a way to make that work. From our initial research, it looks like there is no other way to do that specifically besides pulling Filament into the core and wrapping the available commands similarly to how the library does for Livewire.

But for our specific use case, it is convenient enough to let Filament do some of the lifting when we want to make a new resource.

**Comment by awcodes** [comment]
Thank you for the feedback. I'll see what I can do.

**Comment by AshrafBasry** [comment]
Any new updates on this?
