### ISSUE TITLE
Trying to create {Module}RouteProvider

### ISSUE THREAD

**Issue by walterdis** [InterNACHI/modular#53]
Hello ;)
I'm trying to migrate my application from nwidart module to yours. I have a few questions if you may:
- Have you developed any large applications with this package?
- How can I use my custom RouteProvider to add the API prefix to the routes in the account-routes-api.php file?

I've tried changing the composer.json file for the account module as shown in the screenshot, and I've also created a custom RouteProvider in the Wdc\Account\Providers\AccountRouteProvider file. However, the package still doesn't add the API prefix to the routes.

- account module composer.json 
```
{
  "name": "wdc/account",
  "description": "",
  "type": "library",
  "version": "1.0",
  "license": "proprietary",
  "require": {},
  "autoload": {
    "psr-4": {
      "Wdc\\Account\\": "app/",
      "Wdc\\Account\\Tests\\": "tests/",
      "Wdc\\Account\\Database\\Factories\\": "database/factories/",
      "Wdc\\Account\\Database\\Seeders\\": "database/seeders/"
    }
  },
  "minimum-stability": "stable",
  "extra": {
    "laravel": {
      "providers": [
        "Wdc\\Account\\Providers\\AccountServiceProvider",
        "Wdc\\Account\\Providers\\AccountRouteProvider"
      ]
    }
  }
}

```

- Then in the Wdc\Account\Providers;\AccountRouteProvider:

```
<?php

namespace Wdc\Account\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;


class AccountRouteProvider extends ServiceProvider
{
    public function register()
    {
    }

    public function boot()
    {
        //dd(module_path('account/routes/account-routes-api.php'));
        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->namespace('Wdc\Account\Http\Controllers')
                ->group(module_path('account/routes/account-routes-api.php'));
        });
        //parent::boot();
    }
}
```

helpers.php
```
if (! function_exists('module_path')) {
    function module_path($path = ''): string
    {
        $path = $path
            ? DIRECTORY_SEPARATOR.$path
            : $path;

        $path = 'app-modules'.$path;

        return base_path($path ? DIRECTORY_SEPARATOR.$path : $path);
    }
}
```

The package recognizes account-routes-api, but it doesn't add the API prefix to them. I've verified that AccountRouteProvider is being read by using dd('something').

Thanks for your help´;)

**Comment by walterdis** [comment]
I've changed the code to

```
<?php

namespace Wdc\Account\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;

class AccountRouteProvider extends ServiceProvider
{
    public function register()
    {
    }

    public function boot()
    {
        Route::prefix('api')
            ->middleware('api')
            ->namespace('Wdc\Account\Http\Controllers')
            ->group(module_path('account/routes/account-routes-api.php'));
    }
}

```

and it works now.

I don't know why because I've used RouteServiceProvider as a  base 😄

**Comment by inxilpro** [comment]
Hey, sorry—somehow missed this!

This package is used in a project with about 30 modules, and ~300,000 lines of application code. I don't know if that's big or small to you…

As for the routes issue. I think what's happening is that modular auto-loads anything in a module's `routes/` directory for you. Just get rid of the whole service provider and put the `Route::prefix…` portion inside of `account-routes-api.php`. I think that should solve it for you!

**Comment by doraemonxxx** [comment]
@inxilpro Hi there

when adding a route from the module with middleware, it doesn't work at all, i need to update RouteServiceProvider just to add the app-modules/module/route/module-routes in order to work
