### ISSUE TITLE
Livewire support

### ISSUE THREAD

**Issue by binaryfire** [InterNACHI/modular#54]
Hey Chris

Great package! I'm interested in migrating from my in-house solution but noticed there aren't any Livewire commands / auto-registration features. Is that something you'd consider adding now that Livewire is a first-party Laravel package? https://livewire.laravel.com/

<img width="789" alt="image" src="https://github.com/InterNACHI/modular/assets/5361908/6b1e6bbf-7ca9-4e3f-b42d-407f4d6911a3">
<img width="713" alt="image" src="https://github.com/InterNACHI/modular/assets/5361908/5993a39a-33f9-444b-906b-59761238961f">

Also, how does modular handle namespacing for module names containing more than one word? Eg. I have directories like `modules/admin-users` which are namespaced as `Modules/AdminUsers`.

**Comment by inxilpro** [comment]
We have very basic Livewire support (just `make:livewire`) but would definitely be open to PRs adding more. As for multi-word namespaces—it behaves exactly how you describe. If the module path is `admin-users`, then the namespace would be `AdminUsers`.
