### ISSUE TITLE
[QUESTION]: Converting an existing composer package to a module?

### ISSUE THREAD

**Issue by secondmanveran** [InterNACHI/modular#61]
Hey Guys,

I'm looking to convert some composer packages to modules in order to have full access locally to said package code. 

For example, `jetstream` or `fortify`.

I much prefer your ideology of keeping laravel conventions as opposed to the `laravel-modules` way, but I'm wondering, if I publish and register these modules in packagist, then require those packages in a project, how would they be published back to the `app-modules` directory in the new project so they can be accessed? 

Thanks

**Comment by inxilpro** [comment]
I don't really think modular is right for this. You should look into "path" repositories in composer. For example:

```json
"repositories": [
    {
        "type": "path",
        "url": "/path/to/your/copy/of/jetstream",
        "options": {
            "symlink": true
        }
    }
]
```
