### ISSUE TITLE
Support: How can Use Livewire Volt with InterNACHI/modular

### ISSUE THREAD

**Issue by polodev** [InterNACHI/modular#64]
I like volt due to its colocation features. So I am using volt  component instead of regular livewire component. How can use it?
Thanks

**Comment by benbjurstrom** [comment]
I'm using it with volt. Just needed to mount the module's path in VoltServiceProvider.php

```php
Volt::mount([
    resource_path('views/livewire'),
    resource_path('views/pages'),
    base_path('/app-modules/module/resources/views'),
]);
```

**Comment by polodev** [comment]
Thank you @benbjurstrom
