### ISSUE TITLE
Question for classes in route files

### ISSUE THREAD

**Issue by pavlov80** [InterNACHI/modular#7]
Hey, I found the idea of modular very helpfull for me. 
But I see the example in the generated route file and there we need to import our classes with use clause.
I have very large module with 20 Controllers. Do I need to import all of them and every time when I create new controller or there is other way?

**Comment by inxilpro** [comment]
Right now we don't plan to support the `RouteServiceProvider`-style implicit namespacing, but you can do the same with a group. Something like:

```php
Route::namespace('Modules\MyModule\Http')->group(function() {
	Route::get('/foo', 'FooController@index');
});
```
