### ISSUE TITLE
Merge custom stubs to existing stubs instead of overwriting them

### ISSUE THREAD

**Issue by giuszeppe** [InterNACHI/modular#74]
It could be useful to merge the custom stubs with the existing ones instead of overwriting them. 
For example, I needed to add one file and couldn't figure out how to do it without rewriting all the existing stubs in the code. 
### **Example** 
```
$customStub = [
'test' => base_path('test')
]
$actualStubs = [
... $defaultStubs,
...$customStub
]
```
I hope I was clear, in any case, feel free to ask me any questions. If I missed something and this behavior is feasible without modifying the code, let me know. Thank you!

**Comment by inxilpro** [comment]
Generally, I think if you're managing your own custom stubs it's better to own them all. That way if we make changes to the defaults, it doesn't break yours. You can always compare them to the copies in the repo from time-to-time, but the stubs really don't change much.
