### ISSUE TITLE
OS Windows make:module path failed

### ISSUE THREAD

**Issue by EgorGruzdev** [InterNACHI/modular#8]
Generation does not work on OS Windows, as there is a problem with generated paths.
And therefore, all generations go to the app, and not to the folder with the module.

```php
        //\InterNACHI\Modular\Console\Commands\Make\Modularize
        //it works
        protected function getPath($name)
	{
		if ($module = $this->module()) {
			$name = Str::replaceFirst($module->namespaces->first(), '', $name);
		}

		$path = parent::getPath($name);

		if ($module) {
			// Set up our replacements as a [find -> replace] array
			$replacements = [
				$this->laravel->path() => $module->namespaces->keys()->first(),
				$this->laravel->basePath('tests/Tests') => $module->path('tests'),
				$this->laravel->databasePath() => $module->path('database'),
			];

			// Normalize all our paths for compatibility's sake
			$normalize = function($path) {
			        $path = str_replace(['\\', '/'], [DIRECTORY_SEPARATOR, DIRECTORY_SEPARATOR], $path);
				return trim($path, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR;
			};

			$find = array_map($normalize, array_keys($replacements));
			$replace = array_map($normalize, array_values($replacements));
			// And finally apply the replacements
			$path = str_replace($find, $replace, $normalize($path));
		}

		return rtrim($path, DIRECTORY_SEPARATOR);
	}
```

**Comment by EgorGruzdev** [comment]
PolicyDiscover on Windows for the same reason does not work.

**Comment by adrian-ub** [comment]
I have the same problem, any solution?

**Comment by inxilpro** [comment]
Hm. I don't have a Windows machine to test this on. If you want to submit a PR I'll take a look.

**Comment by EgorGruzdev** [comment]
#13

**Comment by EgorGruzdev** [comment]
Are there any plans to add a cache for the "registerPolicies" method in \InterNACHI\Modular\Support\ModularServiceProvider

**Comment by code-poel** [comment]
This is still broken.

The issue is that there are hard-coded forward-slashes in the `AutoDiscoveryHelper` which need to be replaced with `DIRECTORY_SEPARATOR` constants.

Without this, you get mixed directory separators like this:

`C:\laragon\www\module-test\modules/sandbox/src/Console/Commands`

Which, when you attempt to explode in the `extractModuleNameFromPath` method using the `DIRECTORY_SEPARATOR` constant, results in incorrect results.
