### ISSUE TITLE
Is it compatible with Laravel 8?

### ISSUE THREAD

**Issue by martio** [InterNACHI/modular#9]
Hi! :) Is it compatible with Laravel 8?

**Comment by ejunker** [comment]
I am using it with Laravel 8 and it is working except that I have not been able to get the new model factories to be found but maybe I am doing something wrong. I get an error like this:
`Error : Class 'Database\Factories\CalendarAccountFactory' not found`

**Comment by inxilpro** [comment]
Sorry for such a late response! Yep — the package works fine with Laravel 8 but it doesn't use the new Laravel factories. Support for factory classes will probably come with modular 2.0.
