### ISSUE TITLE
Issue Proposal for Laravel Prompts Integration 

### ISSUE THREAD

**Issue by martin-lechene** [InterNACHI/modular#98]
### Issue Proposal for Laravel Prompts Integration

Hi there!

I'm interested in integrating Laravel Prompts with your project. Specifically, I'd like to inquire whether there are plans to adapt it for Laravel Prompts. If not, I'm eager to take on this task myself.

### Objectives:

1. Create a command `php artisan make:module {?name}` with an optional 'name' parameter.
2. Alternatively, implement a comprehensive command `php artisan module` that offers actions such as module creation and synchronization.
3. Also, consider implementing `php artisan module:make [module name] --[module type]` with an equivalent to `php artisan make:[module type] [name] --module=[module name]`.

I look forward to your thoughts on this proposal!

Best regards !

**Comment by inxilpro** [comment]
We already have a command to make a module, but if you'd like to add prompts into that command I'd definitely be open to a PR!

**Comment by martin-lechene** [comment]
No problem. I work on that's the last week :)
